import json
from database import SessionLocal, engine
import model

products = [
    # --- Autoclaves ---
    {
        "name": "Autoclave de Laboratoire Vertical 50L",
        "description": "Autoclave à vapeur pour la stérilisation d'instruments et de milieux de culture.",
        "category": "autoclaves",
        "price": 2490,
        "image": "https://images.pexels.com/photos/9951400/pexels-photo-9951400.jpeg?auto=compress&cs=tinysrgb&w=1024",
        "long_description": "Autoclave vertical en acier inoxydable 304 avec cuve de 50 litres, conçu pour la stérilisation fiable des instruments de laboratoire, de la verrerie et des milieux de culture. Cycles programmables et sécurité renforcée.",
        "in_stock": True,
        "brand": "LabSteril",
        "model": "AV-50",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Cuve inox 304", "Capacité 50 L", "Écran de contrôle digital", "Cycles programmables", "Système de sécurité double porte"]),
    },
    {
        "name": "Autoclave de Paillasse 24L",
        "description": "Autoclave compact pour petits laboratoires et cabinets dentaires.",
        "category": "autoclaves",
        "price": 1290,
        "image": "https://images.pexels.com/photos/6627664/pexels-photo-6627664.jpeg?auto=compress&cs=tinysrgb&w=1024",
        "long_description": "Autoclave de paillasse compact, idéal pour les cabinets dentaires, vétérinaires et petits laboratoires. Cycle rapide et faible encombrement.",
        "in_stock": True,
        "brand": "LabSteril",
        "model": "AP-24",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Capacité 24 L", "Cycle rapide", "Faible encombrement", "Séchage automatique", "Imprimante de traçabilité en option"]),
    },
    {
        "name": "Autoclave Industriel 100L",
        "description": "Autoclave de grande capacité pour la stérilisation industrielle.",
        "category": "autoclaves",
        "price": 4890,
        "image": "https://images.pexels.com/photos/6627665/pexels-photo-6627665.jpeg?auto=compress&cs=tinysrgb&w=1024",
        "long_description": "Autoclave de grande capacité destiné aux laboratoires industriels et hospitaliers nécessitant des volumes de stérilisation importants.",
        "in_stock": True,
        "brand": "LabSteril",
        "model": "AI-100",
        "condition": "Neuf",
        "year": 2023,
        "features": json.dumps(["Capacité 100 L", "Usage intensif", "Panneau de contrôle avancé", "Registre de traçabilité", "Sécurité renforcée"]),
    },

    # --- Réfrigération de laboratoire ---
    {
        "name": "Réfrigérateur de Laboratoire 300L",
        "description": "Réfrigérateur médical à température régulée pour réactifs et échantillons.",
        "category": "refrigeration",
        "price": 1690,
        "image": "https://d17eythm3w95tp.cloudfront.net/media/207816/conversions/srfvg-5501-medium.png",
        "long_description": "Réfrigérateur de laboratoire à régulation précise de température, adapté à la conservation de réactifs, vaccins et échantillons biologiques.",
        "in_stock": True,
        "brand": "LabCold",
        "model": "RL-300",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Capacité 300 L", "Régulation +2°C à +8°C", "Alarme de température", "Porte vitrée verrouillable", "Enregistreur de données"]),
    },
    {
        "name": "Congélateur -40°C Vertical 200L",
        "description": "Congélateur basse température pour la conservation longue durée d'échantillons.",
        "category": "refrigeration",
        "price": 2990,
        "image": "https://images.pexels.com/photos/8940466/pexels-photo-8940466.jpeg?auto=compress&cs=tinysrgb&w=1024",
        "long_description": "Congélateur vertical atteignant -40°C, conçu pour la conservation longue durée d'échantillons biologiques et de réactifs sensibles.",
        "in_stock": True,
        "brand": "LabCold",
        "model": "CV-40-200",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Température jusqu'à -40°C", "Capacité 200 L", "Isolation renforcée", "Alarme sonore et visuelle", "Batterie de secours en option"]),
    },
    {
        "name": "Chambre Froide de Paillasse 50L",
        "description": "Petite enceinte réfrigérée pour la conservation d'échantillons au poste de travail.",
        "category": "refrigeration",
        "price": 890,
        "image": "https://images.unsplash.com/photo-1646956141021-d687dcfe5fb9?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Enceinte réfrigérée compacte destinée à la conservation immédiate d'échantillons directement au poste de travail.",
        "in_stock": True,
        "brand": "LabCold",
        "model": "CF-50",
        "condition": "Neuf",
        "year": 2023,
        "features": json.dumps(["Capacité 50 L", "Compact", "Faible bruit", "Régulation précise", "Idéal paillasse"]),
    },

    # --- Balances de laboratoire ---
    {
        "name": "Balance Analytique de Précision 0,1mg",
        "description": "Balance analytique haute précision pour la pesée en laboratoire.",
        "category": "balances",
        "price": 890,
        "image": "https://images.unsplash.com/photo-1646956141700-55bd6bc59d95?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Balance analytique offrant une précision de 0,1 mg, adaptée aux laboratoires de chimie, pharmacie et contrôle qualité.",
        "in_stock": True,
        "brand": "LabWeight",
        "model": "BA-01",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Précision 0,1 mg", "Portée 220 g", "Calibration automatique", "Pare-brise en verre", "Écran LCD rétroéclairé"]),
    },
    {
        "name": "Balance de Précision 0,01g",
        "description": "Balance robuste pour les pesées courantes en laboratoire.",
        "category": "balances",
        "price": 349,
        "image": "https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Balance de précision destinée aux pesées courantes en laboratoire, robuste et facile à utiliser au quotidien.",
        "in_stock": True,
        "brand": "LabWeight",
        "model": "BP-02",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Précision 0,01 g", "Portée 2000 g", "Plateau inox", "Fonction tare", "Alimentation secteur ou batterie"]),
    },
    {
        "name": "Balance Compteuse Industrielle",
        "description": "Balance dédiée au comptage de pièces et composants.",
        "category": "balances",
        "price": 590,
        "image": "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Balance compteuse permettant le dénombrement rapide et précis de petites pièces en environnement industriel ou de laboratoire.",
        "in_stock": True,
        "brand": "LabWeight",
        "model": "BC-10",
        "condition": "Neuf",
        "year": 2023,
        "features": json.dumps(["Fonction de comptage", "Portée 3000 g", "Plateau large", "Mémoire multi-produits", "Interface RS-232"]),
    },

    # --- Mobilier de laboratoire ---
    {
        "name": "Banc de Travail de Laboratoire Inox",
        "description": "Table de travail en acier inoxydable pour paillasse de laboratoire.",
        "category": "mobilier",
        "price": 790,
        "image": "https://images.pexels.com/photos/9259926/pexels-photo-9259926.jpeg?auto=compress&cs=tinysrgb&w=1024",
        "long_description": "Banc de travail en acier inoxydable, résistant à la corrosion et facile à nettoyer, adapté à un usage intensif en laboratoire.",
        "in_stock": True,
        "brand": "LabFurn",
        "model": "BT-150",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Acier inoxydable 304", "Surface facile à nettoyer", "Structure renforcée", "Étagère basse incluse", "Dimensions 150x60 cm"]),
    },
    {
        "name": "Armoire de Stockage de Sécurité",
        "description": "Armoire ventilée pour le stockage de produits chimiques.",
        "category": "mobilier",
        "price": 1190,
        "image": "https://images.unsplash.com/photo-1651931802890-b3c066e67100?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Armoire de sécurité ventilée destinée au stockage conforme de produits chimiques et de réactifs sensibles.",
        "in_stock": True,
        "brand": "LabFurn",
        "model": "AS-90",
        "condition": "Neuf",
        "year": 2023,
        "features": json.dumps(["Ventilation intégrée", "Portes verrouillables", "Bac de rétention", "Conforme aux normes de stockage", "Structure métallique renforcée"]),
    },
    {
        "name": "Chaise Ergonomique de Laboratoire",
        "description": "Siège réglable pensé pour un usage prolongé en laboratoire.",
        "category": "mobilier",
        "price": 219,
        "image": "https://images.unsplash.com/photo-1707944745824-c038557dfd7c?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Chaise ergonomique réglable en hauteur, conçue pour le confort du personnel de laboratoire lors de sessions prolongées.",
        "in_stock": True,
        "brand": "LabFurn",
        "model": "CH-05",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Réglage de hauteur", "Assise anti-acide", "Roulettes verrouillables", "Dossier ergonomique", "Facile à désinfecter"]),
    },

    # --- Analyseurs & équipements d'analyse ---
    {
        "name": "Centrifugeuse de Laboratoire 4000 RPM",
        "description": "Centrifugeuse polyvalente pour la séparation d'échantillons.",
        "category": "analyseurs",
        "price": 1590,
        "image": "https://images.unsplash.com/photo-1715442405505-e53ddb9f7d26?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Centrifugeuse de laboratoire atteignant 4000 tr/min, adaptée à la séparation d'échantillons biologiques et chimiques.",
        "in_stock": True,
        "brand": "LabSpin",
        "model": "CL-4000",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Vitesse jusqu'à 4000 RPM", "Rotor interchangeable", "Minuterie programmable", "Freinage automatique", "Faible niveau sonore"]),
    },
    {
        "name": "Incubateur de Laboratoire 150L",
        "description": "Incubateur à température régulée pour cultures cellulaires et microbiologiques.",
        "category": "analyseurs",
        "price": 1990,
        "image": "https://images.unsplash.com/photo-1765830403209-a5eceac4c198?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Incubateur offrant une régulation précise de température et d'humidité, adapté aux cultures cellulaires et microbiologiques.",
        "in_stock": True,
        "brand": "LabGrow",
        "model": "IN-150",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Capacité 150 L", "Régulation de température précise", "Contrôle d'humidité", "Alarme intégrée", "Intérieur inox"]),
    },
    {
        "name": "Bain-Marie de Laboratoire Numérique",
        "description": "Bain-marie à régulation numérique pour incubations et réactions contrôlées.",
        "category": "analyseurs",
        "price": 490,
        "image": "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Bain-marie de laboratoire à régulation numérique de température, adapté aux incubations et réactions contrôlées.",
        "in_stock": True,
        "brand": "LabGrow",
        "model": "BM-20",
        "condition": "Neuf",
        "year": 2023,
        "features": json.dumps(["Régulation numérique", "Capacité 20 L", "Cuve inox", "Couvercle inclus", "Plage 5°C à 99°C"]),
    },
    {
        "name": "Analyseur TOC de Laboratoire",
        "description": "Analyseur de carbone organique total pour le contrôle qualité de l'eau.",
        "category": "analyseurs",
        "price": 6990,
        "image": "https://images.pexels.com/photos/8413159/pexels-photo-8413159.jpeg?auto=compress&cs=tinysrgb&w=1024",
        "long_description": "Analyseur TOC destiné au contrôle qualité de l'eau, utilisé en pharmacie, agroalimentaire et environnement.",
        "in_stock": True,
        "brand": "LabAnalyse",
        "model": "TOC-200",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Mesure du carbone organique total", "Interface logicielle dédiée", "Haute sensibilité", "Étalonnage automatique", "Connectivité USB"]),
    },
    {
        "name": "Analyseur d'Humidité Infrarouge",
        "description": "Analyseur de taux d'humidité par dessiccation infrarouge.",
        "category": "analyseurs",
        "price": 990,
        "image": "https://images.unsplash.com/photo-1777360208554-29a1eba4be0e?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Analyseur d'humidité par dessiccation infrarouge, rapide et précis, adapté aux contrôles qualité en agroalimentaire et pharmacie.",
        "in_stock": True,
        "brand": "LabAnalyse",
        "model": "AH-IR",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Chauffage infrarouge", "Résultats rapides", "Écran tactile", "Mémoire multi-méthodes", "Plateau amovible"]),
    },

    # --- Systèmes de purification d'eau ---
    {
        "name": "Système de Purification d'Eau Type II",
        "description": "Purificateur d'eau de laboratoire pour usages courants.",
        "category": "purification",
        "price": 1390,
        "image": "https://images.unsplash.com/photo-1616996690916-a4d9af24295d?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Système de purification d'eau de type II, adapté à la préparation de réactifs et au nettoyage de verrerie en laboratoire.",
        "in_stock": True,
        "brand": "LabPure",
        "model": "PE-II",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Eau type II", "Débit continu", "Cartouches remplaçables", "Compact", "Faible maintenance"]),
    },
    {
        "name": "Système de Purification d'Eau Ultra-Pure Type I",
        "description": "Purificateur haute performance pour applications analytiques exigeantes.",
        "category": "purification",
        "price": 2790,
        "image": "https://images.pexels.com/photos/8940466/pexels-photo-8940466.jpeg?auto=compress&cs=tinysrgb&w=1024",
        "long_description": "Système de purification d'eau ultra-pure de type I, destiné aux applications analytiques et de recherche les plus exigeantes.",
        "in_stock": True,
        "brand": "LabPure",
        "model": "PE-I",
        "condition": "Neuf",
        "year": 2024,
        "features": json.dumps(["Eau type I ultra-pure", "Résistivité 18,2 MΩ·cm", "Écran de suivi qualité", "Cartouches haute capacité", "Robinet ergonomique"]),
    },
    {
        "name": "Osmoseur de Laboratoire",
        "description": "Système d'osmose inverse pour la préproduction d'eau de laboratoire.",
        "category": "purification",
        "price": 990,
        "image": "https://images.unsplash.com/photo-1646956141021-d687dcfe5fb9?auto=format&fit=crop&w=1024&q=80",
        "long_description": "Système d'osmose inverse permettant la préproduction d'eau à partir de l'eau du réseau, en amont des systèmes de purification.",
        "in_stock": True,
        "brand": "LabPure",
        "model": "OS-100",
        "condition": "Neuf",
        "year": 2023,
        "features": json.dumps(["Membrane osmose inverse", "Réservoir de stockage", "Compact", "Faible consommation", "Installation simple"]),
    },
]

def run():
    """Vide la table produits et la repeuple avec les données de démo."""
    model.Base.metadata.create_all(bind=engine)
    with SessionLocal() as db:
        db.query(model.Product).delete(synchronize_session=False)
        for product_data in products:
            db.add(model.Product(**product_data))
        db.commit()
        print(f"Ajouté {len(products)} produits dans la base.")


if __name__ == "__main__":
    run()